/*
 * This file is generated by jOOQ.
*/
package pl.mati.jooqdemo.model.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import pl.mati.jooqdemo.model.tables.TestTable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestTableRecord extends UpdatableRecordImpl<TestTableRecord> implements Record3<Long, String, Timestamp> {

    private static final long serialVersionUID = 1507169717;

    /**
     * Setter for <code>test.test_table.id</code>.
     */
    public TestTableRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>test.test_table.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>test.test_table.text</code>.
     */
    public TestTableRecord setText(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>test.test_table.text</code>.
     */
    public String getText() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.test_table.creation_dt</code>.
     */
    public TestTableRecord setCreationDt(Timestamp value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>test.test_table.creation_dt</code>.
     */
    public Timestamp getCreationDt() {
        return (Timestamp) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Timestamp> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Timestamp> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TestTable.TEST_TABLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TestTable.TEST_TABLE.TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return TestTable.TEST_TABLE.CREATION_DT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getCreationDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreationDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TestTableRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TestTableRecord value2(String value) {
        setText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TestTableRecord value3(Timestamp value) {
        setCreationDt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TestTableRecord values(Long value1, String value2, Timestamp value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TestTableRecord
     */
    public TestTableRecord() {
        super(TestTable.TEST_TABLE);
    }

    /**
     * Create a detached, initialised TestTableRecord
     */
    public TestTableRecord(Long id, String text, Timestamp creationDt) {
        super(TestTable.TEST_TABLE);

        set(0, id);
        set(1, text);
        set(2, creationDt);
    }
}
