/*
 * This file is generated by jOOQ.
*/
package pl.mati.jooqdemo.model;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;

import pl.mati.jooqdemo.model.tables.TestTable;


/**
 * A class modelling indexes of tables of the <code>test</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index TEST_TABLE_PKEY = Indexes0.TEST_TABLE_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index TEST_TABLE_PKEY = createIndex("test_table_pkey", TestTable.TEST_TABLE, new OrderField[] { TestTable.TEST_TABLE.ID }, true);
    }
}
