/*
 * This file is generated by jOOQ.
*/
package pl.mati.jooqdemo.model;


import javax.annotation.Generated;

import pl.mati.jooqdemo.model.tables.TestTable;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.test_table</code>.
     */
    public static final TestTable TEST_TABLE = pl.mati.jooqdemo.model.tables.TestTable.TEST_TABLE;
}
