SET MODE POSTGRESQL;

CREATE USER app_usr PASSWORD '123';

CREATE SCHEMA TEST;

CREATE TABLE TEST.TEST_TABLE (
  ID BIGINT PRIMARY KEY,
  TEXT VARCHAR,
  CREATION_DT TIMESTAMP
);

CREATE SEQUENCE TEST.TEST_TABLE_PK_SEQ;

GRANT SELECT, UPDATE, INSERT, DELETE ON TEST.TEST_TABLE TO app_usr;