/*
 * This file is generated by jOOQ.
*/
package pl.mati.jooqdemo.model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestTable implements Serializable {

    private static final long serialVersionUID = 1730162246;

    private final Long      id;
    private final String    text;
    private final Timestamp creationDt;

    public TestTable(TestTable value) {
        this.id = value.id;
        this.text = value.text;
        this.creationDt = value.creationDt;
    }

    public TestTable(
        Long      id,
        String    text,
        Timestamp creationDt
    ) {
        this.id = id;
        this.text = text;
        this.creationDt = creationDt;
    }

    public Long getId() {
        return this.id;
    }

    public String getText() {
        return this.text;
    }

    public Timestamp getCreationDt() {
        return this.creationDt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TestTable (");

        sb.append(id);
        sb.append(", ").append(text);
        sb.append(", ").append(creationDt);

        sb.append(")");
        return sb.toString();
    }
}
