/*
 * This file is generated by jOOQ.
*/
package pl.mati.jooqdemo.model.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import pl.mati.jooqdemo.model.Indexes;
import pl.mati.jooqdemo.model.Keys;
import pl.mati.jooqdemo.model.Test;
import pl.mati.jooqdemo.model.tables.records.TestTableRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestTable extends TableImpl<TestTableRecord> {

    private static final long serialVersionUID = 676034115;

    /**
     * The reference instance of <code>test.test_table</code>
     */
    public static final TestTable TEST_TABLE = new TestTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TestTableRecord> getRecordType() {
        return TestTableRecord.class;
    }

    /**
     * The column <code>test.test_table.id</code>.
     */
    public final TableField<TestTableRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>test.test_table.text</code>.
     */
    public final TableField<TestTableRecord, String> TEXT = createField("text", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>test.test_table.creation_dt</code>.
     */
    public final TableField<TestTableRecord, Timestamp> CREATION_DT = createField("creation_dt", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>test.test_table</code> table reference
     */
    public TestTable() {
        this(DSL.name("test_table"), null);
    }

    /**
     * Create an aliased <code>test.test_table</code> table reference
     */
    public TestTable(String alias) {
        this(DSL.name(alias), TEST_TABLE);
    }

    /**
     * Create an aliased <code>test.test_table</code> table reference
     */
    public TestTable(Name alias) {
        this(alias, TEST_TABLE);
    }

    private TestTable(Name alias, Table<TestTableRecord> aliased) {
        this(alias, aliased, null);
    }

    private TestTable(Name alias, Table<TestTableRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Test.TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TEST_TABLE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TestTableRecord> getPrimaryKey() {
        return Keys.TEST_TABLE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TestTableRecord>> getKeys() {
        return Arrays.<UniqueKey<TestTableRecord>>asList(Keys.TEST_TABLE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TestTable as(String alias) {
        return new TestTable(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TestTable as(Name alias) {
        return new TestTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TestTable rename(String name) {
        return new TestTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TestTable rename(Name name) {
        return new TestTable(name, null);
    }
}
